name: build

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # - run: sudo apt remove libgcc-11-dev gcc-11
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang-3.9
          clang++-3.9 -g -O0 -Wall -stdlib=libc++ test.cpp -o test -pthread 
          ./test
  test2:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      # - run: sudo apt remove libgcc-11-dev gcc-11
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang-9
          clang++-9 -g -O0 -Wall -stdlib=libc++ test.cpp -o test -pthread
          ./test