name: build

on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 40
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 20
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 30
          gcc --version
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang-3.9
          clang++-3.9 -g -O0 -Wall -std=gnu++11 test.cpp -o test -pthread
          ./test
  test2:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 40
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 20
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 30
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang-9
          clang++-9 -g -O0 -Wall -std=gnu++11 test.cpp -o test -pthread
          ./test